# Pandas in Python

In [9]:
import numpy as np
import pandas as pd

In [10]:
data = np.random.randint(1,100,15)
data[3]

48

In [11]:
data

array([93, 10, 48, 48, 63, 26, 83, 10, 89,  7, 97, 34, 58, 97,  2])

In [12]:
s = pd.Series(data)

In [13]:
print(s)

0     93
1     10
2     48
3     48
4     63
5     26
6     83
7     10
8     89
9      7
10    97
11    34
12    58
13    97
14     2
dtype: int32


In [14]:
k = [1,2,3,np.nan,'yolo']
k =pd.Series(k)
k

0       1
1       2
2       3
3     NaN
4    yolo
dtype: object

In [15]:
dates = pd.date_range('20180817',periods=6)
dates

DatetimeIndex(['2018-08-17', '2018-08-18', '2018-08-19', '2018-08-20',
               '2018-08-21', '2018-08-22'],
              dtype='datetime64[ns]', freq='D')

In [16]:
st_name=['one','two','three',np.nan,'four','five']
st_data = pd.Series(st_name)
st_data

0      one
1      two
2    three
3      NaN
4     four
5     five
dtype: object

In [17]:
st_data[2]

'three'

In [18]:
st_data.to_excel('st_data.xls')

In [19]:
import datetime

In [20]:
datetime.datetime(2018,7,21,18,35)

datetime.datetime(2018, 7, 21, 18, 35)

In [21]:
import time

In [22]:
time.ctime()

'Sat Jul 21 15:30:46 2018'

In [23]:
np.random.randn(5,2)

array([[-1.82741938, -0.36276331],
       [ 0.19413797, -0.14143971],
       [-0.0385887 ,  2.62415324],
       [-0.1659002 ,  1.305219  ],
       [-0.90924986, -1.04476638]])

In [24]:
st_name = ['Akshay','Ishita','Chippi','bagula']
index = ['Name','Maths','Science']
math = [45,90,70,100]
science = [55,101,60,99]

In [25]:
data = [st_name,math,science]
data

[['Akshay', 'Ishita', 'Chippi', 'bagula'],
 [45, 90, 70, 100],
 [55, 101, 60, 99]]

In [26]:
df = pd.DataFrame(data,index=index,columns=np.arange(4))
df

0       1       2       3
Name     Akshay  Ishita  Chippi  bagula
Maths        45      90      70     100
Science      55     101      60      99

In [27]:
df2 = pd.DataFrame(np.random.randn(6,6),index=dates,columns=list('ABCDEF'))

In [28]:
df2

A         B         C         D         E         F
2018-08-17  0.411724  2.301727 -0.163848 -0.829915 -0.804669  0.524617
2018-08-18 -0.071316 -1.602157 -0.616527 -0.606565 -1.225213  0.182884
2018-08-19  0.619560 -0.797132  0.815978  0.373794  1.362894 -0.792141
2018-08-20  0.032162  1.065269  0.983637  0.375832 -1.520661  0.396516
2018-08-21 -1.215739  0.007776  0.564078  0.347588 -0.090139 -0.985728
2018-08-22  1.332509  1.516141 -1.550431 -0.192441  0.780589  0.450741

In [29]:
df3 = pd.DataFrame({
    'A':[1,2,3],
    'B':pd.Timestamp('20180718'),
    'C':['lol','yolo','GTFO'],
})
df3

A          B     C
0  1 2018-07-18   lol
1  2 2018-07-18  yolo
2  3 2018-07-18  GTFO

In [30]:
df4 = pd.DataFrame({
    'Username':['Jhon','Harry','Natasha','Kiosh','Root'],
    'Date':pd.date_range('20170818',periods=5),
    'Password':['abcdefg','1234567','two@one@g','redhat','Asimov'],
},index=[1,2,3,4,5])
df4

Username       Date   Password
1     Jhon 2017-08-18    abcdefg
2    Harry 2017-08-19    1234567
3  Natasha 2017-08-20  two@one@g
4    Kiosh 2017-08-21     redhat
5     Root 2017-08-22     Asimov

In [31]:
Username = ['Jhon','Harry','Natasha','Kiosh','Root']
Date = pd.date_range('20180715',periods=5)
Password = ['abcdefg','1234567','two@one@g','redhat','Asimov']

In [32]:
#declaring Variables beforehand in this method
df5 = pd.DataFrame({
    'Username': Username,
    'Date': Date,
    'Password': Password,
},index=np.arange(1,6))
df5

Username       Date   Password
1     Jhon 2018-07-15    abcdefg
2    Harry 2018-07-16    1234567
3  Natasha 2018-07-17  two@one@g
4    Kiosh 2018-07-18     redhat
5     Root 2018-07-19     Asimov

In [33]:
df5.head(3)

Username       Date   Password
1     Jhon 2018-07-15    abcdefg
2    Harry 2018-07-16    1234567
3  Natasha 2018-07-17  two@one@g

In [34]:
df5.tail(3)

Username       Date   Password
3  Natasha 2018-07-17  two@one@g
4    Kiosh 2018-07-18     redhat
5     Root 2018-07-19     Asimov

In [35]:
df5.index

Int64Index([1, 2, 3, 4, 5], dtype='int64')

In [36]:
df5.columns

Index(['Username', 'Date', 'Password'], dtype='object')

In [37]:
df5.describe()

Username                 Date Password
count         5                    5        5
unique        5                    5        5
top       Kiosh  2018-07-16 00:00:00   redhat
freq          1                    1        1
first       NaN  2018-07-15 00:00:00      NaN
last        NaN  2018-07-19 00:00:00      NaN

In [38]:
df2.describe()

A         B         C         D         E         F
count  6.000000  6.000000  6.000000  6.000000  6.000000  6.000000
mean   0.184817  0.415271  0.005481 -0.088618 -0.249533 -0.037185
std    0.849488  1.476423  0.975925  0.538216  1.145633  0.672296
min   -1.215739 -1.602157 -1.550431 -0.829915 -1.520661 -0.985728
25%   -0.045446 -0.595905 -0.503357 -0.503034 -1.120077 -0.548385
50%    0.221943  0.536522  0.200115  0.077574 -0.447404  0.289700
75%    0.567601  1.403423  0.753003  0.367242  0.562907  0.437185
max    1.332509  2.301727  0.983637  0.375832  1.362894  0.524617

In [39]:
fd = df.T #to transpose a dataframe
fd

Name Maths Science
0  Akshay    45      55
1  Ishita    90     101
2  Chippi    70      60
3  bagula   100      99

In [40]:
fd.describe()

Name  Maths  Science
count        4      4        4
unique       4      4        4
top     Akshay     70       55
freq         1      1        1

In [41]:
fd.sort_values(by='Maths',ascending=False)

Name Maths Science
3  bagula   100      99
1  Ishita    90     101
2  Chippi    70      60
0  Akshay    45      55

In [42]:
fd.loc[1:4:2,['Maths','Science']]

Maths Science
1    90     101
3   100      99

In [43]:
fd.iloc[:,1]#for getting a single column

0     45
1     90
2     70
3    100
Name: Maths, dtype: object

In [44]:
fd[fd.Maths>80]

Name Maths Science
1  Ishita    90     101
3  bagula   100      99

In [45]:
name = ['x','y','z','p','q']
height = [5.5,5.6,5.8,4.11,6.2]
weight = [65,69,75,43,80]
DOB = ['1-1-1986','7-6-1999','10-5-1996','10-10-2002','15-05-1992']

In [46]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    'Name':name,
    'Height': height,
    'Weight': weight,
},index=np.arange(1,6))

In [47]:
data

Name  Height  Weight
1    x    5.50      65
2    y    5.60      69
3    z    5.80      75
4    p    4.11      43
5    q    6.20      80

In [48]:
salary = [5000,2000,6000,1000,4000]

In [49]:
#to add a column in dataframe or append a dataframe
data['Salary'] = salary

In [50]:
data

Name  Height  Weight  Salary
1    x    5.50      65    5000
2    y    5.60      69    2000
3    z    5.80      75    6000
4    p    4.11      43    1000
5    q    6.20      80    4000

In [51]:
data.loc[:,'Height'] = [5.7,5.1,5.10,5.1,6.4]

In [52]:
data

Name  Height  Weight  Salary
1    x     5.7      65    5000
2    y     5.1      69    2000
3    z     5.1      75    6000
4    p     5.1      43    1000
5    q     6.4      80    4000

In [53]:
data

Name  Height  Weight  Salary
1    x     5.7      65    5000
2    y     5.1      69    2000
3    z     5.1      75    6000
4    p     5.1      43    1000
5    q     6.4      80    4000

In [54]:
olddata = data.copy()

In [55]:
olddata

Name  Height  Weight  Salary
1    x     5.7      65    5000
2    y     5.1      69    2000
3    z     5.1      75    6000
4    p     5.1      43    1000
5    q     6.4      80    4000

In [56]:
np.mean(data['Height'])

5.4799999999999995

In [57]:
data.iloc[:,1]=(sum(olddata.iloc[:,1])/5)

In [58]:
data

Name  Height  Weight  Salary
1    x    5.48      65    5000
2    y    5.48      69    2000
3    z    5.48      75    6000
4    p    5.48      43    1000
5    q    5.48      80    4000

In [59]:
data[data['Weight']<50 ]

Name  Height  Weight  Salary
4    p    5.48      43    1000

In [60]:
data2 = data.copy()

In [61]:
data2

Name  Height  Weight  Salary
1    x    5.48      65    5000
2    y    5.48      69    2000
3    z    5.48      75    6000
4    p    5.48      43    1000
5    q    5.48      80    4000

In [62]:
d = data2['Name'].isin(['p'])

In [63]:
data2[d]

Name  Height  Weight  Salary
4    p    5.48      43    1000

In [64]:
d

1    False
2    False
3    False
4     True
5    False
Name: Name, dtype: bool

In [65]:
data2['Weight'].isin(range(75)) #to check the value within range

1     True
2     True
3    False
4     True
5    False
Name: Weight, dtype: bool

In [66]:
data2[data2['Weight'].isin(range(75))]['Weight'].iloc[:] 

1    65
2    69
4    43
Name: Weight, dtype: int64

In [67]:
data2['Weight'][data2['Weight'].isin(range(75))] += 10 # to incremnet of data in range to given value

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [68]:
data2

Name  Height  Weight  Salary
1    x    5.48      75    5000
2    y    5.48      79    2000
3    z    5.48      75    6000
4    p    5.48      53    1000
5    q    5.48      80    4000

In [69]:
pd.isna(data2)

Name  Height  Weight  Salary
1  False   False   False   False
2  False   False   False   False
3  False   False   False   False
4  False   False   False   False
5  False   False   False   False

In [70]:
data2.mean()

Height       5.48
Weight      72.40
Salary    3600.00
dtype: float64

In [71]:
pd.melt(data2)

variable value
0      Name     x
1      Name     y
2      Name     z
3      Name     p
4      Name     q
5    Height  5.48
6    Height  5.48
7    Height  5.48
8    Height  5.48
9    Height  5.48
10   Weight    75
11   Weight    79
12   Weight    75
13   Weight    53
14   Weight    80
15   Salary  5000
16   Salary  2000
17   Salary  6000
18   Salary  1000
19   Salary  4000

In [76]:
pd.melt(data2,id_vars='Name')

Name variable    value
0     x   Height     5.48
1     y   Height     5.48
2     z   Height     5.48
3     p   Height     5.48
4     q   Height     5.48
5     x   Weight    75.00
6     y   Weight    79.00
7     z   Weight    75.00
8     p   Weight    53.00
9     q   Weight    80.00
10    x   Salary  5000.00
11    y   Salary  2000.00
12    z   Salary  6000.00
13    p   Salary  1000.00
14    q   Salary  4000.00

In [83]:
d=np.random.randint(1,50,25)
d=d.reshape(5,5)
d

array([[40,  2, 25, 35, 33],
       [48,  8, 29, 32, 24],
       [40, 19,  1,  5, 31],
       [29, 32,  7, 45, 44],
       [ 3,  6,  4, 36,  6]])

In [88]:
data2.iat[2,3]

6000

In [95]:
a=4
b=5
if a==4 and b==5:
    print("lol")

lol
